spring.application.name=demo

# 1. Configuração da conexão com o banco de dados H2. Que será rodado na memória.

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 2. Ativa o painel visual do banco no navegador. Para um futuro Dashboard.
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# 3. Faz o Spring mostrar no console os comandos SQL que ele está executando
spring.jpa.show-sql=true
